### ISSUE TITLE
Missing sent DB/txtfile causes AttributeError

### ISSUE THREAD

**Issue by neil-greenwood** [tgray/muttqt#5]
If there is no `sqlfile` or `txtfile` when the `sent` helper is configured, the following exception is thrown:

```
$ ./muttqt -q Joe
Traceback (most recent call last):
  File "./muttqt", line 755, in <module>
    sys.exit(main())
  File "./muttqt", line 738, in main
    data = sentSource.results
AttributeError: 'sentSQLData' object has no attribute 'results'
```

**Comment by masukomi** [comment]
I can confirm this bug and that PR #6 causes the error to go away
