### ISSUE TITLE
'aliasData' object has no attribute 'data'

### ISSUE THREAD

**Issue by tanrax** [tgray/muttqt#7]
```
Juan-MacBook:~ juan$ /usr/local/bin/muttqt -q sonia
Traceback (most recent call last):
  File "/usr/local/bin/muttqt", line 754, in <module>
    sys.exit(main())
  File "/usr/local/bin/muttqt", line 723, in main
    aliasDat.searchData(query)
  File "/usr/local/bin/muttqt", line 56, in searchData
    for l in self.data:
AttributeError: 'aliasData' object has no attribute 'data'
```

**Comment by ekhall** [comment]
Getting this too.

**Comment by rlue** [comment]
@tanrax, @ekhall, have you two seen the [two](https://github.com/tgray/muttqt/issues/3) [other](https://github.com/tgray/muttqt/issues/5) active issues? Make sure that `muttqt.conf` doesn't specify a non-existent mutt alias file in the `[alias]` section or a non-existent sqlfile/txtfile in the `[sent]` section. Or install the commit referenced in @neil-greenwood's PR.
